### ISSUE TITLE
Certificate problem when installing

### ISSUE THREAD

**Issue by hella-schu** [ContaoMonitoring/monitoring-tasks#4]
Hi,
installing failed via composer manager and via SSH. Output of Contao Manager Console: 

 `Loading composer repositories with package information
<warning>The "https://packagist.org/packages.json" file could not be downloaded: SSL operation failed with code 1. OpenSSL Error messages:
error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed
Failed to enable crypto
failed to open stream: operation failed</warning>
<warning>https://packagist.org could not be fully loaded, package information was loaded from the local cache and may be out of date</warning>
Updating dependencies
Package operations: 2 installs, 0 updates, 0 removals
  - Installing contao-monitoring/monitoring (1.9.3): Downloading

    

 <warning>Failed

 to download contao-monitoring/monitoring from dist: The "https://api.github.com/repos/ContaoMonitoring/monitoring/zipball/4fd6972108e4bda3740bcc2b496fd1c4bb5947ea" file could not be downloaded: SSL operation failed with code 1. OpenSSL Error messages:
error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed
Failed to enable crypto
failed to open stream: operation failed</warning>
    <warning>Now trying to download from source</warning>
  - Installing contao-monitoring/monitoring (1.9.3): Cloning 4fd6972108
--------------------------------------------------------
Exception occured: Failed to clone https://github.com/ContaoMonitoring/monitoring.git via https, ssh protocols, aborting.

- https://github.com/ContaoMonitoring/monitoring.git
  Cloning into '/home/www/contao4/vendor/contao-monitoring/monitoring'...
  fatal: unable to access 'https://github.com/ContaoMonitoring/monitoring.git/': server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none

- git@github.com:ContaoMonitoring/monitoring.git
  Cloning into '/home/www/contao4/vendor/contao-monitoring/monitoring'...
  Warning: Permanently added the RSA host key for IP address '192.30.253.113' to the list of known hosts.

  Permission denied (publickey).

  fatal: Could not read from remote repository.
  
  Please make sure you have the correct access rights
  and the repository exists.

#0 phar:///home/www/contao4/web/contao-manager.phar.php/vendor/tenside/core/src/Task/Composer/AbstractComposerCommandTask.php(166): Tenside\Core\Task\Composer\AbstractComposerCommandTask->executeCommand(Object(Composer\Command\UpdateCommand), Object(Symfony\Component\Console\Input\ArrayInput), Object(Tenside\Core\Task\TaskOutput))
#1 phar:///home/www/contao4/web/contao-manager.phar.php/vendor/tenside/core/src/Task/Task.php(173): Tenside\Core\Task\Composer\AbstractComposerCommandTask->doPerform()
#2 phar:///home/www/contao4/web/contao-manager.phar.php/vendor/tenside/core/src/Task/Runner.php(89): Tenside\Core\Task\Task->perform('/home/www/conta...')
#3 phar:///home/www/contao4/web/contao-manager.phar.php/vendor/tenside/core-bundle/src/Command/RunTaskCommand.php(82): Tenside\Core\Task\Runner->run('/home/www/conta...')
#4 phar:///home/www/contao4/web/contao-manager.phar.php/vendor/symfony/console/Command/Command.php(252): Tenside\CoreBundle\Command\RunTaskCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 phar:///home/www/contao4/web/contao-manager.phar.php/vendor/tenside/core-bundle/src/Command/RunTaskCommand.php(61): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 phar:///home/www/contao4/web/contao-manager.phar.php/vendor/symfony/console/Application.php(964): Tenside\CoreBundle\Command\RunTaskCommand->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 phar:///home/www/contao4/web/contao-manager.phar.php/vendor/symfony/console/Application.php(248): Symfony\Component\Console\Application->doRunCommand(Object(Tenside\CoreBundle\Command\RunTaskCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 phar:///home/www/contao4/web/contao-manager.phar.php/api/ApiApplication.php(71): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 phar:///home/www/contao4/web/contao-manager.phar.php/vendor/symfony/console/Application.php(148): Contao\ManagerApi\ApiApplication->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 phar:///home/www/contao4/web/contao-manager.phar.php/api/console(83): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 /home/www/contao4/web/contao-manager.phar.php(55): require('phar:///home/ww...')
#12 {main}
Chained exception: Failed to clone https://github.com/ContaoMonitoring/monitoring.git via https, ssh protocols, aborting.

- https://github.com/ContaoMonitoring/monitoring.git
  Cloning into '/home/www/contao4/vendor/contao-monitoring/monitoring'...
  fatal: unable to access 'https://github.com/ContaoMonitoring/monitoring.git/': server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none

- git@github.com:ContaoMonitoring/monitoring.git
  Cloning into '/home/www/contao4/vendor/contao-monitoring/monitoring'...
  Warning: Permanently added the RSA host key for IP address '192.30.253.113' to the list of known hosts.

  Permission denied (publickey).

  fatal: Could not read from remote repository.
  
  Please make sure you have the correct access rights
  and the repository exists.
`

**Comment by cliffparnitzky** [comment]
Sounds like a packagist probleme, or something on the server. Did you tried  contao-monitoring/bundle-all ???

**Comment by hella-schu** [comment]
yep. Try to get support from hosting company tomorrow. Maybe they know more.

**Comment by cliffparnitzky** [comment]
Okay. Good luck. I will close the ticket.
